import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * 创建侧边栏，你可以通过以下方式之一：
 *
 * - 自动生成：从 docs 文件夹结构自动创建侧边栏
 *   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
 *
 * - 手动创建：显式定义你的侧边栏结构
 *   tutorialSidebar: [
 *     'intro',
 *     'hello',
 *     {
 *       type: 'category',
 *       label: 'Tutorial',
 *       items: ['tutorial-basics/create-a-document'],
 *     },
 *   ],
 */
const sidebars: SidebarsConfig = {
  // 我们使用 'autogenerated' 来让 Docusaurus 根据文件系统结构自动生成侧边栏。
  // 'tutorialSidebar' 是侧边栏的 ID，在 themeConfig.navbar.items 中会用到。
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
